// Domain types. Port of internal/model (review.go, diff.go, scan.go, preview.go).
// JSON field names are a serialization contract — do not rename.
import { z } from 'zod';

export const CATEGORIES = [
  'bug',
  'security',
  'performance',
  'maintainability',
  'test',
  'style',
  'documentation',
  'other',
] as const;
export type Category = (typeof CATEGORIES)[number];

export const SEVERITIES = ['critical', 'high', 'medium', 'low'] as const;
export type Severity = (typeof SEVERITIES)[number];

/** A code review comment generated by the LLM. */
export interface LlmComment {
  path: string;
  content: string;
  suggestion_code?: string;
  existing_code?: string;
  start_line: number;
  end_line: number;
  thinking?: string;
  category?: string;
  severity?: string;
}

export const LlmCommentSchema = z.object({
  path: z.string(),
  content: z.string(),
  suggestion_code: z.string().optional(),
  existing_code: z.string().optional(),
  start_line: z.number().int(),
  end_line: z.number().int(),
  thinking: z.string().optional(),
  category: z.string().optional(),
  severity: z.string().optional(),
});

/** Raw LLM-generated review suggestion for a code segment. */
export interface CodeReviewResult {
  relevant_file: string;
  suggestion_content: string;
  existing_code: string;
  suggestion_code: string;
}

/** A single file change in a git diff. */
export interface Diff {
  old_path: string;
  new_path: string;
  diff: string;
  new_file_content: string;
  is_binary: boolean;
  is_deleted: boolean;
  is_new: boolean;
  is_renamed: boolean;
  insertions: number;
  deletions: number;
}

export function emptyDiff(): Diff {
  return {
    old_path: '',
    new_path: '',
    diff: '',
    new_file_content: '',
    is_binary: false,
    is_deleted: false,
    is_new: false,
    is_renamed: false,
    insertions: 0,
    deletions: 0,
  };
}

/**
 * A single file enumerated by full-scan mode. Unlike Diff (which carries a
 * unified diff text), ScanItem carries the entire file content because scan
 * reviews whole files with no diff context.
 */
export interface ScanItem {
  path: string;
  content: string;
  is_binary?: boolean;
  line_count?: number;
}

/**
 * Adapts a ScanItem to the diff-based shape (line-number resolver,
 * file_read_diff tool). `diff` stays empty; new_file_content carries the
 * whole file so resolveFromFileContent fallbacks still find source lines.
 */
export function scanItemAsDiff(s: ScanItem): Diff {
  return {
    ...emptyDiff(),
    old_path: s.path,
    new_path: s.path,
    new_file_content: s.content,
    is_binary: s.is_binary ?? false,
    insertions: s.line_count ?? 0,
  };
}

/** Why a file was excluded from review. Shared by diff review and full scan. */
export const ExcludeReason = {
  None: '',
  UserRule: 'user_exclude',
  Extension: 'unsupported_ext',
  DefaultPath: 'default_path',
  Deleted: 'deleted',
  Binary: 'binary',
} as const;
export type ExcludeReason = (typeof ExcludeReason)[keyof typeof ExcludeReason];

/** One file's preview record (mode-agnostic). */
export interface PreviewEntry {
  path: string;
  status: string;
  insertions: number;
  deletions: number;
  will_review: boolean;
  exclude_reason?: ExcludeReason;
}

/** Full preview result, rendered the same way for review and scan. */
export interface Preview {
  files: PreviewEntry[];
  total_insertions: number;
  total_deletions: number;
  total_files: number;
  reviewable_count: number;
  excluded_count: number;
}
